require('config/edge')
require('config/illuminate')
require('config/lualine')
require('config/mason')
require('config/nvim-cmp')
require('config/telescope')
require('config/tree')
require('config/tree-sitter')
